spring.application.name=casalfinanceiro

server.port=9095
spring.datasource.url=jdbc:postgresql://localhost:5432/casalfinanceiro
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true