spring.application.name=casalfinanceiro

server.port=9095
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/casalfinanceiro}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.cors.allowed-origins=${CORS_ORIGINS:*}

# Configura��o do JWT com AWS Cognito
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_AWLbCZmGz